# Generated by Django 5.0.6 on 2024-07-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ofertas',
            field=models.IntegerField(default=0),
        ),
    ]
