# Generated by Django 5.0.6 on 2024-07-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_producto_ofertas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='ofertas',
            new_name='oferta',
        ),
    ]
