# Generated by Django 5.0.6 on 2024-07-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_rename_ofertas_producto_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
